/*
 * UtraSonic_init.h
 *
 *  Created on: Mar 1, 2023
 *      Author: LENOVO
 */

#ifndef ULTRA_SONIC_UTRASONIC_INIT_H_
#define ULTRA_SONIC_UTRASONIC_INIT_H_



/* Description:
      • Initialize the ICU driver as required.
      • Setup the ICU call back function.
      • Setup the direction for the trigger pin as output pin through the GPIO driver.
*/
void Ultrasonic_init(void);


/* Description
      • Send the trigger pulse by using Ultrasonic_Trigger function.
      • Start the measurements by the ICU from this moment.
   Return:
      • The measured distance in Centimeter.
*/
u16 Ultrasonic_readDistance(void);


/* Description
      • This is the call back function called by the ICU driver.
      • This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
*/
void Ultrasonic_edgeProcessing(void);

/*function to trigger ULTRASONIC*/
void Ultra_Sonic_Trigger(void);
/*
void H_UltraSonic_Void_Init();
void H_ULTRASONIC_Get_Readings(void);
u16 H_UltraSonic_U16_ReadDistance();
*/


#endif /* ULTRA_SONIC_UTRASONIC_INIT_H_ */
